/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.CustomAlbumPhoto;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomAlbumPhotoRecord extends UpdatableRecordImpl<CustomAlbumPhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.CUSTOM_ALBUM_PHOTO.CUSTOM_ALBUM_ID</code>.
     */
    public void setCustomAlbumId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.CUSTOM_ALBUM_PHOTO.CUSTOM_ALBUM_ID</code>.
     */
    public Long getCustomAlbumId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.CUSTOM_ALBUM_PHOTO.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.CUSTOM_ALBUM_PHOTO.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.CUSTOM_ALBUM_PHOTO.STATE</code>.
     */
    public void setState(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.CUSTOM_ALBUM_PHOTO.STATE</code>.
     */
    public Integer getState() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.CUSTOM_ALBUM_PHOTO.SCENE_GROUP_ID</code>.
     */
    public void setSceneGroupId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.CUSTOM_ALBUM_PHOTO.SCENE_GROUP_ID</code>.
     */
    public Long getSceneGroupId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.CUSTOM_ALBUM_PHOTO.ADDED_AT</code>.
     */
    public void setAddedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.CUSTOM_ALBUM_PHOTO.ADDED_AT</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomAlbumPhotoRecord
     */
    public CustomAlbumPhotoRecord() {
        super(CustomAlbumPhoto.CUSTOM_ALBUM_PHOTO);
    }

    /**
     * Create a detached, initialised CustomAlbumPhotoRecord
     */
    public CustomAlbumPhotoRecord(Long customAlbumId, Long photoId, Integer state, Long sceneGroupId, LocalDateTime addedAt) {
        super(CustomAlbumPhoto.CUSTOM_ALBUM_PHOTO);

        setCustomAlbumId(customAlbumId);
        setPhotoId(photoId);
        setState(state);
        setSceneGroupId(sceneGroupId);
        setAddedAt(addedAt);
        resetChangedOnNotNull();
    }
}
