/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.ImportJobFileIssue;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImportJobFileIssueRecord extends UpdatableRecordImpl<ImportJobFileIssueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.IMPORT_JOB_FILE_ISSUE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_FILE_ISSUE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_FILE_ISSUE.FILE_PATH</code>.
     */
    public void setFilePath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_FILE_ISSUE.FILE_PATH</code>.
     */
    public String getFilePath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_FILE_ISSUE.ISSUE_TYPE</code>.
     */
    public void setIssueType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_FILE_ISSUE.ISSUE_TYPE</code>.
     */
    public String getIssueType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_FILE_ISSUE.REASON</code>.
     */
    public void setReason(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_FILE_ISSUE.REASON</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_FILE_ISSUE.RUN_ID</code>.
     */
    public void setRunId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_FILE_ISSUE.RUN_ID</code>.
     */
    public Long getRunId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImportJobFileIssueRecord
     */
    public ImportJobFileIssueRecord() {
        super(ImportJobFileIssue.IMPORT_JOB_FILE_ISSUE);
    }

    /**
     * Create a detached, initialised ImportJobFileIssueRecord
     */
    public ImportJobFileIssueRecord(Long id, String filePath, String issueType, String reason, Long runId) {
        super(ImportJobFileIssue.IMPORT_JOB_FILE_ISSUE);

        setId(id);
        setFilePath(filePath);
        setIssueType(issueType);
        setReason(reason);
        setRunId(runId);
        resetChangedOnNotNull();
    }
}
