/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.ImportJobStats;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImportJobStatsRecord extends UpdatableRecordImpl<ImportJobStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.JOB_TYPE</code>.
     */
    public void setJobType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.JOB_TYPE</code>.
     */
    public String getJobType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.ROOT_PATHS_JSON</code>.
     */
    public void setRootPathsJson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.ROOT_PATHS_JSON</code>.
     */
    public String getRootPathsJson() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.STARTED_AT</code>.
     */
    public void setStartedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.STARTED_AT</code>.
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.FINISHED_AT</code>.
     */
    public void setFinishedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.FINISHED_AT</code>.
     */
    public LocalDateTime getFinishedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.PHOTO_IMPORTED_COUNT</code>.
     */
    public void setPhotoImportedCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.PHOTO_IMPORTED_COUNT</code>.
     */
    public Long getPhotoImportedCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.PHOTO_UPDATED_COUNT</code>.
     */
    public void setPhotoUpdatedCount(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.PHOTO_UPDATED_COUNT</code>.
     */
    public Long getPhotoUpdatedCount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.VIDEO_IMPORTED_COUNT</code>.
     */
    public void setVideoImportedCount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.VIDEO_IMPORTED_COUNT</code>.
     */
    public Long getVideoImportedCount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.VIDEO_UPDATED_COUNT</code>.
     */
    public void setVideoUpdatedCount(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.VIDEO_UPDATED_COUNT</code>.
     */
    public Long getVideoUpdatedCount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.BYTES_IMPORTED</code>.
     */
    public void setBytesImported(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.BYTES_IMPORTED</code>.
     */
    public Long getBytesImported() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.SKIPPED_UNCHANGED_COUNT</code>.
     */
    public void setSkippedUnchangedCount(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.SKIPPED_UNCHANGED_COUNT</code>.
     */
    public Long getSkippedUnchangedCount() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.UNSUPPORTED_CODEC_COUNT</code>.
     */
    public void setUnsupportedCodecCount(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.UNSUPPORTED_CODEC_COUNT</code>.
     */
    public Long getUnsupportedCodecCount() {
        return (Long) get(12);
    }

    /**
     * Setter for
     * <code>public.IMPORT_JOB_STATS.UNSUPPORTED_EXTENSION_COUNT</code>.
     */
    public void setUnsupportedExtensionCount(Long value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>public.IMPORT_JOB_STATS.UNSUPPORTED_EXTENSION_COUNT</code>.
     */
    public Long getUnsupportedExtensionCount() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.IMPORT_JOB_STATS.FAILURES_JSON</code>.
     */
    public void setFailuresJson(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.IMPORT_JOB_STATS.FAILURES_JSON</code>.
     */
    public String getFailuresJson() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImportJobStatsRecord
     */
    public ImportJobStatsRecord() {
        super(ImportJobStats.IMPORT_JOB_STATS);
    }

    /**
     * Create a detached, initialised ImportJobStatsRecord
     */
    public ImportJobStatsRecord(Long id, String jobType, String rootPathsJson, String status, LocalDateTime startedAt, LocalDateTime finishedAt, Long photoImportedCount, Long photoUpdatedCount, Long videoImportedCount, Long videoUpdatedCount, Long bytesImported, Long skippedUnchangedCount, Long unsupportedCodecCount, Long unsupportedExtensionCount, String failuresJson) {
        super(ImportJobStats.IMPORT_JOB_STATS);

        setId(id);
        setJobType(jobType);
        setRootPathsJson(rootPathsJson);
        setStatus(status);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
        setPhotoImportedCount(photoImportedCount);
        setPhotoUpdatedCount(photoUpdatedCount);
        setVideoImportedCount(videoImportedCount);
        setVideoUpdatedCount(videoUpdatedCount);
        setBytesImported(bytesImported);
        setSkippedUnchangedCount(skippedUnchangedCount);
        setUnsupportedCodecCount(unsupportedCodecCount);
        setUnsupportedExtensionCount(unsupportedExtensionCount);
        setFailuresJson(failuresJson);
        resetChangedOnNotNull();
    }
}
