/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.KeyboardShortcut;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KeyboardShortcutRecord extends UpdatableRecordImpl<KeyboardShortcutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.KEYBOARD_SHORTCUT.ACTION_ID</code>.
     */
    public void setActionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.KEYBOARD_SHORTCUT.ACTION_ID</code>.
     */
    public String getActionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.KEYBOARD_SHORTCUT.KEY_COMBINATION</code>.
     */
    public void setKeyCombination(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.KEYBOARD_SHORTCUT.KEY_COMBINATION</code>.
     */
    public String getKeyCombination() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.KEYBOARD_SHORTCUT.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.KEYBOARD_SHORTCUT.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KeyboardShortcutRecord
     */
    public KeyboardShortcutRecord() {
        super(KeyboardShortcut.KEYBOARD_SHORTCUT);
    }

    /**
     * Create a detached, initialised KeyboardShortcutRecord
     */
    public KeyboardShortcutRecord(String actionId, String keyCombination, LocalDateTime updatedAt) {
        super(KeyboardShortcut.KEYBOARD_SHORTCUT);

        setActionId(actionId);
        setKeyCombination(keyCombination);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
