/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.MediaMetadataEdit;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaMetadataEditRecord extends UpdatableRecordImpl<MediaMetadataEditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.MEDIA_ID</code>.
     */
    public void setMediaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.MEDIA_ID</code>.
     */
    public Long getMediaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.FIELD_NAME</code>.
     */
    public void setFieldName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.FIELD_NAME</code>.
     */
    public String getFieldName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.OLD_VALUE</code>.
     */
    public void setOldValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.OLD_VALUE</code>.
     */
    public String getOldValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.NEW_VALUE</code>.
     */
    public void setNewValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.NEW_VALUE</code>.
     */
    public String getNewValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.EDIT_TYPE</code>.
     */
    public void setEditType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.EDIT_TYPE</code>.
     */
    public String getEditType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.MEDIA_METADATA_EDIT.EDITED_AT</code>.
     */
    public void setEditedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.MEDIA_METADATA_EDIT.EDITED_AT</code>.
     */
    public LocalDateTime getEditedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaMetadataEditRecord
     */
    public MediaMetadataEditRecord() {
        super(MediaMetadataEdit.MEDIA_METADATA_EDIT);
    }

    /**
     * Create a detached, initialised MediaMetadataEditRecord
     */
    public MediaMetadataEditRecord(Long id, Long mediaId, String fieldName, String oldValue, String newValue, String editType, LocalDateTime editedAt) {
        super(MediaMetadataEdit.MEDIA_METADATA_EDIT);

        setId(id);
        setMediaId(mediaId);
        setFieldName(fieldName);
        setOldValue(oldValue);
        setNewValue(newValue);
        setEditType(editType);
        setEditedAt(editedAt);
        resetChangedOnNotNull();
    }
}
