/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.SceneGroup;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SceneGroupRecord extends UpdatableRecordImpl<SceneGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.SCENE_GROUP.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.SCENE_GROUP.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.SCENE_GROUP.CUSTOM_ALBUM_ID</code>.
     */
    public void setCustomAlbumId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.SCENE_GROUP.CUSTOM_ALBUM_ID</code>.
     */
    public Long getCustomAlbumId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SceneGroupRecord
     */
    public SceneGroupRecord() {
        super(SceneGroup.SCENE_GROUP);
    }

    /**
     * Create a detached, initialised SceneGroupRecord
     */
    public SceneGroupRecord(Long id, Long customAlbumId) {
        super(SceneGroup.SCENE_GROUP);

        setId(id);
        setCustomAlbumId(customAlbumId);
        resetChangedOnNotNull();
    }
}
