/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.CustomAlbum.CustomAlbumPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.SceneGroup.SceneGroupPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.CustomAlbumPhotoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomAlbumPhoto extends TableImpl<CustomAlbumPhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.CUSTOM_ALBUM_PHOTO</code>
     */
    public static final CustomAlbumPhoto CUSTOM_ALBUM_PHOTO = new CustomAlbumPhoto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomAlbumPhotoRecord> getRecordType() {
        return CustomAlbumPhotoRecord.class;
    }

    /**
     * The column <code>public.CUSTOM_ALBUM_PHOTO.CUSTOM_ALBUM_ID</code>.
     */
    public final TableField<CustomAlbumPhotoRecord, Long> CUSTOM_ALBUM_ID = createField(DSL.name("CUSTOM_ALBUM_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM_PHOTO.PHOTO_ID</code>.
     */
    public final TableField<CustomAlbumPhotoRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM_PHOTO.STATE</code>.
     */
    public final TableField<CustomAlbumPhotoRecord, Short> STATE = createField(DSL.name("STATE"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM_PHOTO.SCENE_GROUP_ID</code>.
     */
    public final TableField<CustomAlbumPhotoRecord, Long> SCENE_GROUP_ID = createField(DSL.name("SCENE_GROUP_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM_PHOTO.ADDED_AT</code>.
     */
    public final TableField<CustomAlbumPhotoRecord, LocalDateTime> ADDED_AT = createField(DSL.name("ADDED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private CustomAlbumPhoto(Name alias, Table<CustomAlbumPhotoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomAlbumPhoto(Name alias, Table<CustomAlbumPhotoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.CUSTOM_ALBUM_PHOTO</code> table reference
     */
    public CustomAlbumPhoto(String alias) {
        this(DSL.name(alias), CUSTOM_ALBUM_PHOTO);
    }

    /**
     * Create an aliased <code>public.CUSTOM_ALBUM_PHOTO</code> table reference
     */
    public CustomAlbumPhoto(Name alias) {
        this(alias, CUSTOM_ALBUM_PHOTO);
    }

    /**
     * Create a <code>public.CUSTOM_ALBUM_PHOTO</code> table reference
     */
    public CustomAlbumPhoto() {
        this(DSL.name("CUSTOM_ALBUM_PHOTO"), null);
    }

    public <O extends Record> CustomAlbumPhoto(Table<O> path, ForeignKey<O, CustomAlbumPhotoRecord> childPath, InverseForeignKey<O, CustomAlbumPhotoRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOM_ALBUM_PHOTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class CustomAlbumPhotoPath extends CustomAlbumPhoto implements Path<CustomAlbumPhotoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomAlbumPhotoPath(Table<O> path, ForeignKey<O, CustomAlbumPhotoRecord> childPath, InverseForeignKey<O, CustomAlbumPhotoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomAlbumPhotoPath(Name alias, Table<CustomAlbumPhotoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomAlbumPhotoPath as(String alias) {
            return new CustomAlbumPhotoPath(DSL.name(alias), this);
        }

        @Override
        public CustomAlbumPhotoPath as(Name alias) {
            return new CustomAlbumPhotoPath(alias, this);
        }

        @Override
        public CustomAlbumPhotoPath as(Table<?> alias) {
            return new CustomAlbumPhotoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CUSTOM_ALBUM_PHOTO_ALBUM, Indexes.IDX_CUSTOM_ALBUM_PHOTO_SCENE_GROUP, Indexes.IDX_CUSTOM_ALBUM_PHOTO_STATE);
    }

    @Override
    public UniqueKey<CustomAlbumPhotoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_BFD23;
    }

    @Override
    public List<ForeignKey<CustomAlbumPhotoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_BF, Keys.CONSTRAINT_BFD, Keys.CONSTRAINT_BFD2);
    }

    private transient CustomAlbumPath _customAlbum;

    /**
     * Get the implicit join path to the <code>public.CUSTOM_ALBUM</code> table.
     */
    public CustomAlbumPath customAlbum() {
        if (_customAlbum == null)
            _customAlbum = new CustomAlbumPath(this, Keys.CONSTRAINT_BF, null);

        return _customAlbum;
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_BFD, null);

        return _media;
    }

    private transient SceneGroupPath _sceneGroup;

    /**
     * Get the implicit join path to the <code>public.SCENE_GROUP</code> table.
     */
    public SceneGroupPath sceneGroup() {
        if (_sceneGroup == null)
            _sceneGroup = new SceneGroupPath(this, Keys.CONSTRAINT_BFD2, null);

        return _sceneGroup;
    }

    @Override
    public CustomAlbumPhoto as(String alias) {
        return new CustomAlbumPhoto(DSL.name(alias), this);
    }

    @Override
    public CustomAlbumPhoto as(Name alias) {
        return new CustomAlbumPhoto(alias, this);
    }

    @Override
    public CustomAlbumPhoto as(Table<?> alias) {
        return new CustomAlbumPhoto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbumPhoto rename(String name) {
        return new CustomAlbumPhoto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbumPhoto rename(Name name) {
        return new CustomAlbumPhoto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbumPhoto rename(Table<?> name) {
        return new CustomAlbumPhoto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto where(Condition condition) {
        return new CustomAlbumPhoto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbumPhoto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbumPhoto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbumPhoto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbumPhoto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbumPhoto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
