/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.CustomAlbumPhoto.CustomAlbumPhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.SceneGroup.SceneGroupPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.CustomAlbumRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomAlbum extends TableImpl<CustomAlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.CUSTOM_ALBUM</code>
     */
    public static final CustomAlbum CUSTOM_ALBUM = new CustomAlbum();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomAlbumRecord> getRecordType() {
        return CustomAlbumRecord.class;
    }

    /**
     * The column <code>public.CUSTOM_ALBUM.ID</code>.
     */
    public final TableField<CustomAlbumRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM.NAME</code>.
     */
    public final TableField<CustomAlbumRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM.COVER_PHOTO_ID</code>.
     */
    public final TableField<CustomAlbumRecord, Long> COVER_PHOTO_ID = createField(DSL.name("COVER_PHOTO_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM.CREATED_AT</code>.
     */
    public final TableField<CustomAlbumRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.CUSTOM_ALBUM.UPDATED_AT</code>.
     */
    public final TableField<CustomAlbumRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private CustomAlbum(Name alias, Table<CustomAlbumRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomAlbum(Name alias, Table<CustomAlbumRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.CUSTOM_ALBUM</code> table reference
     */
    public CustomAlbum(String alias) {
        this(DSL.name(alias), CUSTOM_ALBUM);
    }

    /**
     * Create an aliased <code>public.CUSTOM_ALBUM</code> table reference
     */
    public CustomAlbum(Name alias) {
        this(alias, CUSTOM_ALBUM);
    }

    /**
     * Create a <code>public.CUSTOM_ALBUM</code> table reference
     */
    public CustomAlbum() {
        this(DSL.name("CUSTOM_ALBUM"), null);
    }

    public <O extends Record> CustomAlbum(Table<O> path, ForeignKey<O, CustomAlbumRecord> childPath, InverseForeignKey<O, CustomAlbumRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOM_ALBUM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class CustomAlbumPath extends CustomAlbum implements Path<CustomAlbumRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomAlbumPath(Table<O> path, ForeignKey<O, CustomAlbumRecord> childPath, InverseForeignKey<O, CustomAlbumRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomAlbumPath(Name alias, Table<CustomAlbumRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomAlbumPath as(String alias) {
            return new CustomAlbumPath(DSL.name(alias), this);
        }

        @Override
        public CustomAlbumPath as(Name alias) {
            return new CustomAlbumPath(alias, this);
        }

        @Override
        public CustomAlbumPath as(Table<?> alias) {
            return new CustomAlbumPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CustomAlbumRecord, Long> getIdentity() {
        return (Identity<CustomAlbumRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomAlbumRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    @Override
    public List<ForeignKey<CustomAlbumRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_EB);
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_EB, null);

        return _media;
    }

    private transient SceneGroupPath _sceneGroup;

    /**
     * Get the implicit to-many join path to the <code>public.SCENE_GROUP</code>
     * table
     */
    public SceneGroupPath sceneGroup() {
        if (_sceneGroup == null)
            _sceneGroup = new SceneGroupPath(this, null, Keys.CONSTRAINT_BAA.getInverseKey());

        return _sceneGroup;
    }

    private transient CustomAlbumPhotoPath _customAlbumPhoto;

    /**
     * Get the implicit to-many join path to the
     * <code>public.CUSTOM_ALBUM_PHOTO</code> table
     */
    public CustomAlbumPhotoPath customAlbumPhoto() {
        if (_customAlbumPhoto == null)
            _customAlbumPhoto = new CustomAlbumPhotoPath(this, null, Keys.CONSTRAINT_BF.getInverseKey());

        return _customAlbumPhoto;
    }

    @Override
    public CustomAlbum as(String alias) {
        return new CustomAlbum(DSL.name(alias), this);
    }

    @Override
    public CustomAlbum as(Name alias) {
        return new CustomAlbum(alias, this);
    }

    @Override
    public CustomAlbum as(Table<?> alias) {
        return new CustomAlbum(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbum rename(String name) {
        return new CustomAlbum(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbum rename(Name name) {
        return new CustomAlbum(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomAlbum rename(Table<?> name) {
        return new CustomAlbum(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum where(Condition condition) {
        return new CustomAlbum(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbum where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbum where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbum where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomAlbum where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomAlbum whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
