/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportJobFileIssue.ImportJobFileIssuePath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.ImportJobStatsRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImportJobStats extends TableImpl<ImportJobStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.IMPORT_JOB_STATS</code>
     */
    public static final ImportJobStats IMPORT_JOB_STATS = new ImportJobStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImportJobStatsRecord> getRecordType() {
        return ImportJobStatsRecord.class;
    }

    /**
     * The column <code>public.IMPORT_JOB_STATS.ID</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.JOB_TYPE</code>.
     */
    public final TableField<ImportJobStatsRecord, String> JOB_TYPE = createField(DSL.name("JOB_TYPE"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.ROOT_PATHS_JSON</code>.
     */
    public final TableField<ImportJobStatsRecord, String> ROOT_PATHS_JSON = createField(DSL.name("ROOT_PATHS_JSON"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.STATUS</code>.
     */
    public final TableField<ImportJobStatsRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.STARTED_AT</code>.
     */
    public final TableField<ImportJobStatsRecord, LocalDateTime> STARTED_AT = createField(DSL.name("STARTED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.FINISHED_AT</code>.
     */
    public final TableField<ImportJobStatsRecord, LocalDateTime> FINISHED_AT = createField(DSL.name("FINISHED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.PHOTO_IMPORTED_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> PHOTO_IMPORTED_COUNT = createField(DSL.name("PHOTO_IMPORTED_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.PHOTO_UPDATED_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> PHOTO_UPDATED_COUNT = createField(DSL.name("PHOTO_UPDATED_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.VIDEO_IMPORTED_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> VIDEO_IMPORTED_COUNT = createField(DSL.name("VIDEO_IMPORTED_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.VIDEO_UPDATED_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> VIDEO_UPDATED_COUNT = createField(DSL.name("VIDEO_UPDATED_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.BYTES_IMPORTED</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> BYTES_IMPORTED = createField(DSL.name("BYTES_IMPORTED"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.SKIPPED_UNCHANGED_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> SKIPPED_UNCHANGED_COUNT = createField(DSL.name("SKIPPED_UNCHANGED_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_STATS.UNSUPPORTED_CODEC_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> UNSUPPORTED_CODEC_COUNT = createField(DSL.name("UNSUPPORTED_CODEC_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.IMPORT_JOB_STATS.UNSUPPORTED_EXTENSION_COUNT</code>.
     */
    public final TableField<ImportJobStatsRecord, Long> UNSUPPORTED_EXTENSION_COUNT = createField(DSL.name("UNSUPPORTED_EXTENSION_COUNT"), SQLDataType.BIGINT.nullable(false), this, "");

    private ImportJobStats(Name alias, Table<ImportJobStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ImportJobStats(Name alias, Table<ImportJobStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.IMPORT_JOB_STATS</code> table reference
     */
    public ImportJobStats(String alias) {
        this(DSL.name(alias), IMPORT_JOB_STATS);
    }

    /**
     * Create an aliased <code>public.IMPORT_JOB_STATS</code> table reference
     */
    public ImportJobStats(Name alias) {
        this(alias, IMPORT_JOB_STATS);
    }

    /**
     * Create a <code>public.IMPORT_JOB_STATS</code> table reference
     */
    public ImportJobStats() {
        this(DSL.name("IMPORT_JOB_STATS"), null);
    }

    public <O extends Record> ImportJobStats(Table<O> path, ForeignKey<O, ImportJobStatsRecord> childPath, InverseForeignKey<O, ImportJobStatsRecord> parentPath) {
        super(path, childPath, parentPath, IMPORT_JOB_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class ImportJobStatsPath extends ImportJobStats implements Path<ImportJobStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ImportJobStatsPath(Table<O> path, ForeignKey<O, ImportJobStatsRecord> childPath, InverseForeignKey<O, ImportJobStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ImportJobStatsPath(Name alias, Table<ImportJobStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImportJobStatsPath as(String alias) {
            return new ImportJobStatsPath(DSL.name(alias), this);
        }

        @Override
        public ImportJobStatsPath as(Name alias) {
            return new ImportJobStatsPath(alias, this);
        }

        @Override
        public ImportJobStatsPath as(Table<?> alias) {
            return new ImportJobStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ImportJobStatsRecord, Long> getIdentity() {
        return (Identity<ImportJobStatsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ImportJobStatsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B6F;
    }

    private transient ImportJobFileIssuePath _importJobFileIssue;

    /**
     * Get the implicit to-many join path to the
     * <code>public.IMPORT_JOB_FILE_ISSUE</code> table
     */
    public ImportJobFileIssuePath importJobFileIssue() {
        if (_importJobFileIssue == null)
            _importJobFileIssue = new ImportJobFileIssuePath(this, null, Keys.FK_IMPORT_JOB_FILE_ISSUE_RUN.getInverseKey());

        return _importJobFileIssue;
    }

    @Override
    public ImportJobStats as(String alias) {
        return new ImportJobStats(DSL.name(alias), this);
    }

    @Override
    public ImportJobStats as(Name alias) {
        return new ImportJobStats(alias, this);
    }

    @Override
    public ImportJobStats as(Table<?> alias) {
        return new ImportJobStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobStats rename(String name) {
        return new ImportJobStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobStats rename(Name name) {
        return new ImportJobStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobStats rename(Table<?> name) {
        return new ImportJobStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats where(Condition condition) {
        return new ImportJobStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
