/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportJobStats.ImportJobStatsPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.ImportJobFileIssueRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImportJobFileIssue extends TableImpl<ImportJobFileIssueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.IMPORT_JOB_FILE_ISSUE</code>
     */
    public static final ImportJobFileIssue IMPORT_JOB_FILE_ISSUE = new ImportJobFileIssue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImportJobFileIssueRecord> getRecordType() {
        return ImportJobFileIssueRecord.class;
    }

    /**
     * The column <code>public.IMPORT_JOB_FILE_ISSUE.ID</code>.
     */
    public final TableField<ImportJobFileIssueRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.IMPORT_JOB_FILE_ISSUE.FILE_PATH</code>.
     */
    public final TableField<ImportJobFileIssueRecord, String> FILE_PATH = createField(DSL.name("FILE_PATH"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_FILE_ISSUE.ISSUE_TYPE</code>.
     */
    public final TableField<ImportJobFileIssueRecord, String> ISSUE_TYPE = createField(DSL.name("ISSUE_TYPE"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_FILE_ISSUE.REASON</code>.
     */
    public final TableField<ImportJobFileIssueRecord, String> REASON = createField(DSL.name("REASON"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.IMPORT_JOB_FILE_ISSUE.RUN_ID</code>.
     */
    public final TableField<ImportJobFileIssueRecord, Long> RUN_ID = createField(DSL.name("RUN_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private ImportJobFileIssue(Name alias, Table<ImportJobFileIssueRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ImportJobFileIssue(Name alias, Table<ImportJobFileIssueRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.IMPORT_JOB_FILE_ISSUE</code> table
     * reference
     */
    public ImportJobFileIssue(String alias) {
        this(DSL.name(alias), IMPORT_JOB_FILE_ISSUE);
    }

    /**
     * Create an aliased <code>public.IMPORT_JOB_FILE_ISSUE</code> table
     * reference
     */
    public ImportJobFileIssue(Name alias) {
        this(alias, IMPORT_JOB_FILE_ISSUE);
    }

    /**
     * Create a <code>public.IMPORT_JOB_FILE_ISSUE</code> table reference
     */
    public ImportJobFileIssue() {
        this(DSL.name("IMPORT_JOB_FILE_ISSUE"), null);
    }

    public <O extends Record> ImportJobFileIssue(Table<O> path, ForeignKey<O, ImportJobFileIssueRecord> childPath, InverseForeignKey<O, ImportJobFileIssueRecord> parentPath) {
        super(path, childPath, parentPath, IMPORT_JOB_FILE_ISSUE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class ImportJobFileIssuePath extends ImportJobFileIssue implements Path<ImportJobFileIssueRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ImportJobFileIssuePath(Table<O> path, ForeignKey<O, ImportJobFileIssueRecord> childPath, InverseForeignKey<O, ImportJobFileIssueRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ImportJobFileIssuePath(Name alias, Table<ImportJobFileIssueRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImportJobFileIssuePath as(String alias) {
            return new ImportJobFileIssuePath(DSL.name(alias), this);
        }

        @Override
        public ImportJobFileIssuePath as(Name alias) {
            return new ImportJobFileIssuePath(alias, this);
        }

        @Override
        public ImportJobFileIssuePath as(Table<?> alias) {
            return new ImportJobFileIssuePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IMPORT_JOB_FILE_ISSUE_RUN_ID);
    }

    @Override
    public Identity<ImportJobFileIssueRecord, Long> getIdentity() {
        return (Identity<ImportJobFileIssueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ImportJobFileIssueRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_58;
    }

    @Override
    public List<ForeignKey<ImportJobFileIssueRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_IMPORT_JOB_FILE_ISSUE_RUN);
    }

    private transient ImportJobStatsPath _importJobStats;

    /**
     * Get the implicit join path to the <code>public.IMPORT_JOB_STATS</code>
     * table.
     */
    public ImportJobStatsPath importJobStats() {
        if (_importJobStats == null)
            _importJobStats = new ImportJobStatsPath(this, Keys.FK_IMPORT_JOB_FILE_ISSUE_RUN, null);

        return _importJobStats;
    }

    @Override
    public ImportJobFileIssue as(String alias) {
        return new ImportJobFileIssue(DSL.name(alias), this);
    }

    @Override
    public ImportJobFileIssue as(Name alias) {
        return new ImportJobFileIssue(alias, this);
    }

    @Override
    public ImportJobFileIssue as(Table<?> alias) {
        return new ImportJobFileIssue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobFileIssue rename(String name) {
        return new ImportJobFileIssue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobFileIssue rename(Name name) {
        return new ImportJobFileIssue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportJobFileIssue rename(Table<?> name) {
        return new ImportJobFileIssue(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue where(Condition condition) {
        return new ImportJobFileIssue(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobFileIssue where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobFileIssue where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobFileIssue where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportJobFileIssue where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportJobFileIssue whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
