/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.records.KeyboardShortcutRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KeyboardShortcut extends TableImpl<KeyboardShortcutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.KEYBOARD_SHORTCUT</code>
     */
    public static final KeyboardShortcut KEYBOARD_SHORTCUT = new KeyboardShortcut();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeyboardShortcutRecord> getRecordType() {
        return KeyboardShortcutRecord.class;
    }

    /**
     * The column <code>public.KEYBOARD_SHORTCUT.ACTION_ID</code>.
     */
    public final TableField<KeyboardShortcutRecord, String> ACTION_ID = createField(DSL.name("ACTION_ID"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.KEYBOARD_SHORTCUT.KEY_COMBINATION</code>.
     */
    public final TableField<KeyboardShortcutRecord, String> KEY_COMBINATION = createField(DSL.name("KEY_COMBINATION"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.KEYBOARD_SHORTCUT.UPDATED_AT</code>.
     */
    public final TableField<KeyboardShortcutRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private KeyboardShortcut(Name alias, Table<KeyboardShortcutRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private KeyboardShortcut(Name alias, Table<KeyboardShortcutRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.KEYBOARD_SHORTCUT</code> table reference
     */
    public KeyboardShortcut(String alias) {
        this(DSL.name(alias), KEYBOARD_SHORTCUT);
    }

    /**
     * Create an aliased <code>public.KEYBOARD_SHORTCUT</code> table reference
     */
    public KeyboardShortcut(Name alias) {
        this(alias, KEYBOARD_SHORTCUT);
    }

    /**
     * Create a <code>public.KEYBOARD_SHORTCUT</code> table reference
     */
    public KeyboardShortcut() {
        this(DSL.name("KEYBOARD_SHORTCUT"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<KeyboardShortcutRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_29;
    }

    @Override
    public KeyboardShortcut as(String alias) {
        return new KeyboardShortcut(DSL.name(alias), this);
    }

    @Override
    public KeyboardShortcut as(Name alias) {
        return new KeyboardShortcut(alias, this);
    }

    @Override
    public KeyboardShortcut as(Table<?> alias) {
        return new KeyboardShortcut(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyboardShortcut rename(String name) {
        return new KeyboardShortcut(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyboardShortcut rename(Name name) {
        return new KeyboardShortcut(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyboardShortcut rename(Table<?> name) {
        return new KeyboardShortcut(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut where(Condition condition) {
        return new KeyboardShortcut(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeyboardShortcut where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeyboardShortcut where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeyboardShortcut where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KeyboardShortcut where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KeyboardShortcut whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
