/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.MediaMetadataEditRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaMetadataEdit extends TableImpl<MediaMetadataEditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.MEDIA_METADATA_EDIT</code>
     */
    public static final MediaMetadataEdit MEDIA_METADATA_EDIT = new MediaMetadataEdit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaMetadataEditRecord> getRecordType() {
        return MediaMetadataEditRecord.class;
    }

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.ID</code>.
     */
    public final TableField<MediaMetadataEditRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.MEDIA_ID</code>.
     */
    public final TableField<MediaMetadataEditRecord, Long> MEDIA_ID = createField(DSL.name("MEDIA_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.FIELD_NAME</code>.
     */
    public final TableField<MediaMetadataEditRecord, String> FIELD_NAME = createField(DSL.name("FIELD_NAME"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.OLD_VALUE</code>.
     */
    public final TableField<MediaMetadataEditRecord, String> OLD_VALUE = createField(DSL.name("OLD_VALUE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.NEW_VALUE</code>.
     */
    public final TableField<MediaMetadataEditRecord, String> NEW_VALUE = createField(DSL.name("NEW_VALUE"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.EDIT_TYPE</code>.
     */
    public final TableField<MediaMetadataEditRecord, String> EDIT_TYPE = createField(DSL.name("EDIT_TYPE"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_METADATA_EDIT.EDITED_AT</code>.
     */
    public final TableField<MediaMetadataEditRecord, LocalDateTime> EDITED_AT = createField(DSL.name("EDITED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private MediaMetadataEdit(Name alias, Table<MediaMetadataEditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaMetadataEdit(Name alias, Table<MediaMetadataEditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.MEDIA_METADATA_EDIT</code> table reference
     */
    public MediaMetadataEdit(String alias) {
        this(DSL.name(alias), MEDIA_METADATA_EDIT);
    }

    /**
     * Create an aliased <code>public.MEDIA_METADATA_EDIT</code> table reference
     */
    public MediaMetadataEdit(Name alias) {
        this(alias, MEDIA_METADATA_EDIT);
    }

    /**
     * Create a <code>public.MEDIA_METADATA_EDIT</code> table reference
     */
    public MediaMetadataEdit() {
        this(DSL.name("MEDIA_METADATA_EDIT"), null);
    }

    public <O extends Record> MediaMetadataEdit(Table<O> path, ForeignKey<O, MediaMetadataEditRecord> childPath, InverseForeignKey<O, MediaMetadataEditRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_METADATA_EDIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MediaMetadataEditPath extends MediaMetadataEdit implements Path<MediaMetadataEditRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaMetadataEditPath(Table<O> path, ForeignKey<O, MediaMetadataEditRecord> childPath, InverseForeignKey<O, MediaMetadataEditRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaMetadataEditPath(Name alias, Table<MediaMetadataEditRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaMetadataEditPath as(String alias) {
            return new MediaMetadataEditPath(DSL.name(alias), this);
        }

        @Override
        public MediaMetadataEditPath as(Name alias) {
            return new MediaMetadataEditPath(alias, this);
        }

        @Override
        public MediaMetadataEditPath as(Table<?> alias) {
            return new MediaMetadataEditPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_MEDIA_METADATA_EDIT_MEDIA_FIELD);
    }

    @Override
    public Identity<MediaMetadataEditRecord, Long> getIdentity() {
        return (Identity<MediaMetadataEditRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MediaMetadataEditRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7D;
    }

    @Override
    public List<ForeignKey<MediaMetadataEditRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_7D7);
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_7D7, null);

        return _media;
    }

    @Override
    public MediaMetadataEdit as(String alias) {
        return new MediaMetadataEdit(DSL.name(alias), this);
    }

    @Override
    public MediaMetadataEdit as(Name alias) {
        return new MediaMetadataEdit(alias, this);
    }

    @Override
    public MediaMetadataEdit as(Table<?> alias) {
        return new MediaMetadataEdit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaMetadataEdit rename(String name) {
        return new MediaMetadataEdit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaMetadataEdit rename(Name name) {
        return new MediaMetadataEdit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaMetadataEdit rename(Table<?> name) {
        return new MediaMetadataEdit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit where(Condition condition) {
        return new MediaMetadataEdit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaMetadataEdit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaMetadataEdit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaMetadataEdit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaMetadataEdit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaMetadataEdit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
