/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.CustomAlbum.CustomAlbumPath;
import com.github.curiousoddman.curious_images.dbobj.tables.CustomAlbumPhoto.CustomAlbumPhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.SceneGroupRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SceneGroup extends TableImpl<SceneGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.SCENE_GROUP</code>
     */
    public static final SceneGroup SCENE_GROUP = new SceneGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SceneGroupRecord> getRecordType() {
        return SceneGroupRecord.class;
    }

    /**
     * The column <code>public.SCENE_GROUP.ID</code>.
     */
    public final TableField<SceneGroupRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.SCENE_GROUP.CUSTOM_ALBUM_ID</code>.
     */
    public final TableField<SceneGroupRecord, Long> CUSTOM_ALBUM_ID = createField(DSL.name("CUSTOM_ALBUM_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private SceneGroup(Name alias, Table<SceneGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SceneGroup(Name alias, Table<SceneGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.SCENE_GROUP</code> table reference
     */
    public SceneGroup(String alias) {
        this(DSL.name(alias), SCENE_GROUP);
    }

    /**
     * Create an aliased <code>public.SCENE_GROUP</code> table reference
     */
    public SceneGroup(Name alias) {
        this(alias, SCENE_GROUP);
    }

    /**
     * Create a <code>public.SCENE_GROUP</code> table reference
     */
    public SceneGroup() {
        this(DSL.name("SCENE_GROUP"), null);
    }

    public <O extends Record> SceneGroup(Table<O> path, ForeignKey<O, SceneGroupRecord> childPath, InverseForeignKey<O, SceneGroupRecord> parentPath) {
        super(path, childPath, parentPath, SCENE_GROUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class SceneGroupPath extends SceneGroup implements Path<SceneGroupRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SceneGroupPath(Table<O> path, ForeignKey<O, SceneGroupRecord> childPath, InverseForeignKey<O, SceneGroupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SceneGroupPath(Name alias, Table<SceneGroupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SceneGroupPath as(String alias) {
            return new SceneGroupPath(DSL.name(alias), this);
        }

        @Override
        public SceneGroupPath as(Name alias) {
            return new SceneGroupPath(alias, this);
        }

        @Override
        public SceneGroupPath as(Table<?> alias) {
            return new SceneGroupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SCENE_GROUP_ALBUM);
    }

    @Override
    public Identity<SceneGroupRecord, Long> getIdentity() {
        return (Identity<SceneGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SceneGroupRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_BA;
    }

    @Override
    public List<ForeignKey<SceneGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_BAA);
    }

    private transient CustomAlbumPath _customAlbum;

    /**
     * Get the implicit join path to the <code>public.CUSTOM_ALBUM</code> table.
     */
    public CustomAlbumPath customAlbum() {
        if (_customAlbum == null)
            _customAlbum = new CustomAlbumPath(this, Keys.CONSTRAINT_BAA, null);

        return _customAlbum;
    }

    private transient CustomAlbumPhotoPath _customAlbumPhoto;

    /**
     * Get the implicit to-many join path to the
     * <code>public.CUSTOM_ALBUM_PHOTO</code> table
     */
    public CustomAlbumPhotoPath customAlbumPhoto() {
        if (_customAlbumPhoto == null)
            _customAlbumPhoto = new CustomAlbumPhotoPath(this, null, Keys.CONSTRAINT_BFD2.getInverseKey());

        return _customAlbumPhoto;
    }

    @Override
    public SceneGroup as(String alias) {
        return new SceneGroup(DSL.name(alias), this);
    }

    @Override
    public SceneGroup as(Name alias) {
        return new SceneGroup(alias, this);
    }

    @Override
    public SceneGroup as(Table<?> alias) {
        return new SceneGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SceneGroup rename(String name) {
        return new SceneGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SceneGroup rename(Name name) {
        return new SceneGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SceneGroup rename(Table<?> name) {
        return new SceneGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup where(Condition condition) {
        return new SceneGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SceneGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SceneGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SceneGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SceneGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SceneGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
