CREATE TABLE IMPORT_JOB_STATS
(
    ID                          BIGSERIAl PRIMARY KEY,
    JOB_TYPE                    VARCHAR(32) NOT NULL,
    ROOT_PATHS_JSON             VARCHAR     NOT NULL,
    STATUS                      VARCHAR(32) NOT NULL,
    STARTED_AT                  TIMESTAMP   NOT NULL,
    FINISHED_AT                 TIMESTAMP,
    PHOTO_IMPORTED_COUNT        BIGINT      NOT NULL,
    PHOTO_UPDATED_COUNT         BIGINT      NOT NULL,
    VIDEO_IMPORTED_COUNT        BIGINT      NOT NULL,
    VIDEO_UPDATED_COUNT         BIGINT      NOT NULL,
    BYTES_IMPORTED              BIGINT      NOT NULL,
    SKIPPED_UNCHANGED_COUNT     BIGINT      NOT NULL,
    UNSUPPORTED_CODEC_COUNT     BIGINT      NOT NULL,
    UNSUPPORTED_EXTENSION_COUNT BIGINT      NOT NULL
);

CREATE TABLE IMPORT_JOB_FILE_ISSUE
(
    ID         BIGSERIAl PRIMARY KEY,
    FILE_PATH  VARCHAR     NOT NULL,
    ISSUE_TYPE VARCHAR(16) NOT NULL, -- SKIPPED | FAILED — see ImportFileIssueType
    REASON     VARCHAR     NOT NULL,
    RUN_ID     BIGINT      NOT NULL,
    CONSTRAINT FK_IMPORT_JOB_FILE_ISSUE_RUN FOREIGN KEY (RUN_ID) REFERENCES IMPORT_JOB_STATS (ID)
);

CREATE INDEX IDX_IMPORT_JOB_FILE_ISSUE_RUN_ID ON IMPORT_JOB_FILE_ISSUE (RUN_ID);
