CREATE TABLE MEDIA_METADATA_EDIT
(
    ID         BIGSERIAL PRIMARY KEY,
    MEDIA_ID   BIGINT       NOT NULL REFERENCES MEDIA (ID) ON DELETE CASCADE,
    FIELD_NAME VARCHAR(64)  NOT NULL, -- 'ROTATION' | 'CAPTURE_DATE'
    OLD_VALUE  VARCHAR(255),          -- stringified previous value, null if it was unset
    NEW_VALUE  VARCHAR(255) NOT NULL, -- stringified new value
    EDIT_TYPE  VARCHAR(32)  NOT NULL, -- 'ABSOLUTE' | 'RELATIVE' (RELATIVE only meaningful for ROTATION)
    EDITED_AT  TIMESTAMP    NOT NULL
);

CREATE INDEX IDX_MEDIA_METADATA_EDIT_MEDIA_FIELD ON MEDIA_METADATA_EDIT (MEDIA_ID, FIELD_NAME);
